# Embeds the service-definition templates from packaging/ into a generated header, so the
# installer inside the binary and the files shipped for packagers can never drift apart.
function(kcf_embed_templates output)
    set(names macos_launch_agent linux_systemd_unit)
    set(files packaging/macos/launch-agent.plist.in packaging/linux/keyboard-chatter-filter.service.in)

    set(content "// Generated by cmake/EmbedTemplates.cmake. Do not edit.\n#pragma once\n\nnamespace kcf::templates {\n")
    foreach(name file IN ZIP_LISTS names files)
        set(path "${PROJECT_SOURCE_DIR}/${file}")
        file(READ "${path}" text)
        string(FIND "${text}" ")KCF_TEMPLATE\"" clash)
        if(NOT clash EQUAL -1)
            message(FATAL_ERROR "${file} contains the raw-string delimiter")
        endif()
        string(APPEND content "\ninline constexpr const char* k_${name} = R\"KCF_TEMPLATE(${text})KCF_TEMPLATE\";\n")
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${path}")
    endforeach()
    string(APPEND content "\n}  // namespace kcf::templates\n")

    file(WRITE "${output}.tmp" "${content}")
    configure_file("${output}.tmp" "${output}" COPYONLY)
    file(REMOVE "${output}.tmp")
endfunction()
